### ISSUE TITLE
데이터셋의 상업적이용가능성

### ISSUE THREAD

**Issue by changdaeoh** [nlpai-lab/KULLM#13]
안녕하세요, 과제 수행을 위해 오픈소스 instruction dataset을 수집중인 대학원생입니다.
우선 너무 좋은 프로젝트 결과물 공개해주셔서 감사드립니다.

KULLM-v2 데이터셋을 부분적으로, 상업적으로 이용하여도 괜찮은지 여쭤보고 싶습니다.

3가지 데이터소스 (gpt4all, vicuna, dolly) 중
* gpt4all 데이터셋은 상업적으로 이용이 불가능함이 테크리포트에 명시되어있고 
* vicuna의학습에 사용된 데이터셋은 openai LLM로부터의 generated output로부터 구축되어 openai의 이용 조항을 따라야 하고 
* dolly의 경우에는, 데이터셋을 상업적으로 이용가능함이 오피셜깃헙에 기재되어있는데요,

KULLM-v2 중 dolly소스 데이터만 추출하여, 이를 저희팀이 상업적으로 이용할 새로운 LLM학습 데이터의 일부로써 사용하여도 괜찮을지 여쭤보고싶습니다.

**Comment by taeminlee** [comment]
안녕하세요, 저희가 번역한 데이터 셋은 원 데이터 셋의 라이센스를 따르고 있습니다.
말씀해주신 것과 같이 gpt4all, vicuna의 경우 사용이 어려울 것 이며, dolly는 사용이 가능할 것 입니다.
dolly의 경우 https://huggingface.co/datasets/nlpai-lab/databricks-dolly-15k-ko 에서 다운로드 가능합니다.
감사합니다.
