### ISSUE TITLE
데이터 번역 방식 질문

### ISSUE THREAD

**Issue by zzong2006** [nlpai-lab/KULLM#15]
안녕하세요. deepl 로 데이터셋(https://huggingface.co/datasets/nlpai-lab/kullm-v2) 을 번역하셨다고 했는데요.

deepl API 는 8월 기준으로 현재 한국에서 서비스가 불가능한것으로 알고있습니다. 

어떤식으로 15만개정도의 데이터셋을 모두 번역하셨을까요? 방법이 궁금하여 질문드립니다.

**Comment by taeminlee** [comment]
답변일 기준 한국에서도 유료 API 서비스가 개시되었습니다. deepl 사이트에서 API 계정 가입 후 카드 결제하시면 될 것입니다.

저희가 작업할 당시는 해외에 거주하시는 분의 도움을 받아 pro API를 사용하였습니다.
