### ISSUE TITLE
user_oriented_instructions_eval.jsonl 로 평가하는 코드도 공유 해주실 수 있을까요? 

### ISSUE THREAD

**Issue by justinbuzzni** [nlpai-lab/KULLM#2]
안녕하세요. 
이런게 있으면 좋겠다 싶었는데, 이런 좋은 모델과, 자료를 공유해 주셔서 감사합니다. 
평가를 따라 해보고 싶은데요, user_oriented_instructions_eval.jsonl 이 데이터를 사용해서 평가한 코드를 공유 해주실 수 있을까요?

**Comment by nlpai-lab** [comment]
안녕하세요 먼저 관심 가져 주셔서 감사합니다. 
평가 코드는 다양한 모델에 대해 실험을 진행한 후에 프롬프트를 공개 할 예정입니다. 

감사합니다.
