### ISSUE TITLE
안녕하세요. 속도 관련해서 질문 드립니다. 

### ISSUE THREAD

**Issue by moondriller** [nlpai-lab/KULLM#4]
현재 tesla t4 15g gpu 4기를 사용하여 모델을 사용해보았습니다. 
모델에서 답변이 나오기까지 약 3분 이상이 걸립니다. 
이 문제를 해결하기 위한 방법이 있을까요?

**Comment by metterian** [comment]
안녕하세요. 저희는 README에 작성된 것과 같이 A100 4대를 사용해서 학습과 추론을 진행했습니다. 
Tesla T4의 경우 A100의 비해 단순 텐서 코어 갯수가 부족합니다. 
A100을 1장을 사용할 경우 한 답변에 평균 30초 이상이 소요 됩니다. 

- Tesla T4: T4는 16GB의 GDDR6 메모리와  2,560개의 CUDA 코어
- A100: A100은 80GB의 VRAM 메모리를 갖추고 있고, 6,912 CUDA 코어

결론적으로, T4와 A100은 매우 다른 종류의 작업에 적합하게 설계되었습니다. T4는 비교적 가벼운 추론 작업에 적합하며, A100은 무거운 훈련 작업이나 복잡한 계산 작업에 더 적합합니다. 때문에  물리적 한계가 존재 함으로  적합한 GPU를 선택하시길 바랍니다 .
