### ISSUE TITLE
안녕하세요 !! 질문이 있습니다.

### ISSUE THREAD

**Issue by Kang812** [nlpai-lab/KULLM#7]
우선 이런 프로젝트를 공개해 주신것에 대해서 감사드립니다.

우선, 저는 training 시키는 코드를 활용해서 공개해주신 데이터 셋을 사용해서 모델을 학습시키는 과정을 진행을 했고,
best 모델이 save 되었습니다.

학습한 모델을 load해서 사용하기 위해서는

tokenizer_config.json
tokenizer.json
special_tokens_map.json
pytorch_model.bin.index.json
config.json

과 같은 json 파일들이 필요하다는 것을 알게 되었습니다.
하지만, 해당 파일들이 생성이 되지 않아서 학습한 모델을 load 할 수 없는 상황입니다.

학습한 모델을 기준으로한 json 파일들을 만들 수 있는 방법이 있을까요 ..  ?

**Comment by metterian** [comment]
꼭 학습한 모델을 load하기 위해서 json 파일들이 요구 되지는 않습니다만, 
HuggingFace (HF)의 model save output 형태로 만들경우 json 파일이 생성됩니다. 
그러므로, HF model output을 만드는 법을 설명드리겠습니다. 

해당 ouput 파일을 만들기 위해서는 레포지토리에서 [export_hf_checkpoint.py](https://github.com/nlpai-lab/KULLM/blob/master/export_hf_checkpoint.py) 파일을 구동 시키면 됩니다. 

감사합니다.

**Comment by metterian** [comment]
추가로 용이한 사용을 위해 LoRA weight를 병합하여 HF model output으로 출력하는 코드([merge_lora.py](https://github.com/nlpai-lab/KULLM/blob/master/merge_lora.py)) 작성했습니다. 

이용에 도움 되길 바랍니다.

**Comment by kwbyun** [comment]
감사합니다 !!

**Comment by Kang812** [comment]
![image](https://github.com/nlpai-lab/KULLM/assets/69283127/e989e5c9-e0e2-46c7-ba3e-fedb2de9ff9a)

다음과 같은 error가 발생을 합니다 !! OSError: ./work_dir/checkpoint-28200 does not appear to have a file named config.json
